Add Getting Start Page
lubusIN/wpui pull request #28
Opened 2024-06-12 10:08 UTC by deepakgithub11

Closes #18 
added getting started button page
added md file also applied some CSS on file

2024-06-13 07:52 UTC, ajitbohra requested changes
Need changes

2024-06-13 07:52 UTC, ajitbohra commented on src/components/gettingstarted.js
this should got under `pages`

2024-06-13 07:52 UTC, ajitbohra commented on src/components/gettingstarted.js
> +import "./md.css"
organize imports as external, WordPress and Internal

2024-06-13 07:52 UTC, ajitbohra commented on src/components/gs.md
this should go under `docs` folder all md files in one location

2024-06-13 07:52 UTC, ajitbohra commented on src/components/index.js
> +export { default as Gettingstarted } from './gettingstarted';
Should be under pages.

2024-06-13 07:52 UTC, ajitbohra commented on src/components/md.css
should be in styles > docs.css under src

2024-06-13 07:57 UTC, ajitbohra approved these changes

2024-06-13 07:57 UTC, ajitbohra commented on src/components/md.css
> +    border: 1px solid black;
remove border here

2024-06-13 08:10 UTC, deepakgithub11 commented on src/components/md.css
do we have ti make new folder for al css???

2024-06-13 14:17 UTC, ajitbohra requested changes

2024-06-13 14:17 UTC, ajitbohra commented on src/Doc/doc.css
the folder name should be a small case `doc` `doc.css` should be under styles folder

2024-06-13 14:17 UTC, ajitbohra commented on src/Doc/getting-started.md
folder name should be small case `doc`

2024-06-13 14:20 UTC, ajitbohra requested changes

2024-06-13 14:20 UTC, ajitbohra commented on src/components/banner.js
> +                            variant="secondary"
remove variant as it adds blue border to button

2024-06-14 22:48 UTC, ajitbohra requested changes

2024-06-14 22:48 UTC, ajitbohra commented on src/Doc/getting-started.md
folder name should be `doc` all small case

2024-06-14 22:48 UTC, ajitbohra commented on src/components/banner.js
> + * WordPress dependencies.
```suggestion
 * External dependencies.
```

2024-06-16 03:10 UTC, deepakgithub11 commented
added build folder in .gitignore in futher PR build will be ignored

2024-06-16 03:20 UTC, deepakgithub11 commented
added build folder in .gitignore in further PR build will be ignored

2024-06-18 04:53 UTC, ajitbohra approved these changes
👍

2024-06-18 04:53 UTC, merged