replace: replace banner img to SVG
lubusIN/wpui pull request #62
Opened 2024-06-28 11:23 UTC by deepakgithub11

2024-06-28 11:26 UTC, deepakgithub11 commented
reponsive and scss file for index file is still pending for banner svg

2024-06-28 13:26 UTC, ajitbohra requested changes

2024-06-28 13:26 UTC, ajitbohra commented on src/app.scss
> +        background-color: transparent !important;
what do we need this ?

2024-06-28 13:26 UTC, ajitbohra commented on src/components/banner/index.js
> +                <svg className="svg"
extract this `SVG` into a separate component under `src/components` as `HeroBackground` or `BannerBackground`

2024-06-28 13:34 UTC, ajitbohra commented
**_Issues:_**

We have the following issues:

**_Desktop_**
<img width="1792" alt="Screenshot 2024-06-28 at 7 02 30 PM" src="https://github.com/lubusIN/wpui/assets/1039236/e2c05736-1942-4bdf-9fc7-9605d28801e8">

**_Mobile_**
<img width="428" alt="Screenshot 2024-06-28 at 7 03 54 PM" src="https://github.com/lubusIN/wpui/assets/1039236/9e0c8c7b-97e5-4b4f-907e-cb7d55e0e1c7">

2024-07-01 07:15 UTC, deepakgithub11 commented
banner is now responsive on phone

2024-07-01 10:41 UTC, ajitbohra commented
Still banner is broken on both desktop and mobile!

2024-07-08 05:56 UTC, deepakgithub11 commented
banner svg is now responsive

2024-07-11 05:36 UTC, closed without merging