refract(page): getting started page re-organized
lubusIN/wpui pull request #63
Opened 2024-07-01 08:17 UTC by deepakgithub11

background color for blocks is light
border added to each blocks(div)

2024-07-01 10:34 UTC, ajitbohra requested changes

2024-07-01 10:34 UTC, ajitbohra commented on src/app.scss
> +    border: 0.5px solid black;
border color should be the shade of grey.

2024-07-01 10:34 UTC, ajitbohra commented on src/app.scss
> +.getting-started {
keep classname generic to allow reuse

2024-07-01 10:34 UTC, ajitbohra commented on src/pages/getting-started.js
> +    <div className="getting-started">
keep the classname generic to allow reuse

2024-07-01 16:32 UTC, deepakgithub11 commented
new CSS applied for border color

2024-07-02 04:54 UTC, ajitbohra requested changes

2024-07-02 04:54 UTC, ajitbohra commented on src/app.scss
> +    background-color: rgb(231 231 231);
```suggestion
    background-color: #f0f0f0;
```

2024-07-02 05:14 UTC, deepakgithub11 commented
background color changed
I request you not to close this branch as the getting started page is not responsive for now
I will continue this branch for responsive commit

2024-07-02 05:14 UTC, merged