refactor footer
lubusIN/wpui pull request #79
Opened 2024-07-29 07:15 UTC by deepakgithub11

This PR is for footer changes.

2024-07-29 07:15 UTC, deepakgithub11 commented
for now flag png is used will replace later with svg once svg is available.

2024-07-29 09:14 UTC, deepakgithub11 commented
IMG replaced with SVG
changes done for logo SVG
all Figma changes applied

2024-07-31 13:48 UTC, ajitbohra requested changes
need a few code changes, functionality wise looks good.

2024-07-31 13:48 UTC, ajitbohra commented on src/components/banner/style.scss
> +    padding-right: 12px;
```suggestion
    padding: 7px 12px;
```

we can use the shorthand

2024-07-31 13:48 UTC, ajitbohra commented on src/components/footer/index.js
> +let Year = date.getFullYear();
```suggestion
const Year = date.getFullYear();
```

2024-07-31 13:48 UTC, ajitbohra commented on src/components/footer/index.js
> +                <VStack className="sec-1" alignment="center" spacing={4}>
```suggestion
                <VStack className="footer-content" alignment="center" spacing={4}>
```

class can be more descriptive!

2024-07-31 13:48 UTC, ajitbohra commented on src/components/footer/index.js
> +                    <Text className='wpui-footer-bottoml' color='white'>&copy; {Year} WPUI. All Rights Reserved.</Text>
```suggestion
                    <Text className='wpui-footer-bottom-left' color='white'>&copy; {Year} WPUI. All Rights Reserved.</Text>
```

2024-07-31 13:48 UTC, ajitbohra commented on src/components/footer/index.js
> +                    <HStack expanded={false} spacing={1}  className='wpui-footer-bottomr'>
```suggestion
                    <HStack expanded={false} spacing={1}  className='wpui-footer-bottom-right'>
```

2024-08-02 14:39 UTC, merged