add Shell (1) Pattern
lubusIN/wpui pull request #87
Opened 2024-08-26 14:02 UTC by deepakgithub11

This PR adds a new shell 1 pattern for WPUI

2024-08-26 14:03 UTC, deepakgithub11 commented
Ready For Review

2024-08-26 16:10 UTC, ajitbohra requested changes

2024-08-26 16:10 UTC, ajitbohra commented on src/categories/index.js
> +export { default as Shell } from './shell';
```suggestion
export { default as Shells } from './shells';
```

2024-08-26 16:10 UTC, ajitbohra commented on src/categories/shell.js
> +function Shell() {
```suggestion
function Shells() {
```

2024-08-26 16:10 UTC, ajitbohra commented on src/categories/shell.js
> +export default Shell;
```suggestion
export default Shells;
```

2024-08-26 16:10 UTC, ajitbohra commented on src/categories/shell.js
fille name should be shells.js

2024-08-26 16:10 UTC, ajitbohra commented on src/patterns/Shell/shell1.js
folder should be Shells

2024-08-26 16:10 UTC, ajitbohra commented on src/patterns/index.js
> +export * as Shell  from './Shell';
```suggestion
export * as Shell  from './Shells';
```

2024-08-26 16:12 UTC, ajitbohra commented on src/categories/shell.js
> +Shell.meta = {
```suggestion
Shells.meta = {
```

2024-08-26 16:13 UTC, ajitbohra commented on src/categories/shell.js
> +  patterns: patterns.Shell,
```suggestion
  patterns: patterns.Shells,
```

2024-08-26 16:13 UTC, ajitbohra commented on src/categories/shell.js
> +  path: '/shell',
```suggestion
  path: '/shells',
```

2024-08-26 16:13 UTC, ajitbohra commented on src/categories/shell.js
> +export default Shell;
```suggestion
export default Shells
```

2024-08-27 05:34 UTC, Verma-Punit commented on src/patterns/Shells/shell1.js
> +                    <HStack expanded={false} style={{ marginLeft: '5px' }}>
Remove the HStack do not wrap the img tag within it

2024-08-27 05:35 UTC, Verma-Punit commented on src/patterns/Shells/shell1.js
> +                        <img width='100px' style={{minWidth:'100px'}} src="https://raw.githubusercontent.com/lubusIN/wpui/main/src/img/logo.png"></img>
Remove the HStack do not wrap the img tag within it

2024-08-27 05:37 UTC, Verma-Punit commented on src/patterns/Shells/shell1.js
> +                    <Heading style={{ padding: '20px', marginLeft: '10px' }}>Dashboard</Heading>
Remove the inline style it will affect responsiveness.

2024-08-27 05:38 UTC, Verma-Punit commented on src/patterns/Shells/shell1.js
> +                    <Card style={{ backgroundColor: '#F0F0F1', height: '300px', margin: '30px 30px', borderRadius: '10px' }}>
Remove the margin style it will affect responsiveness.

2024-08-31 07:36 UTC, merged